name: Cache-Clean

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Projects
        uses: actions/checkout@main

      - name: Cache Clean
        run: gh cache delete --all || true
